services:
  - type: web
    name: github-activity-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: COMMIT_FREQUENCY
        value: "*/30 * * * *"
