services:
  - type: web
    name: github-activity-bot
    env: node
    buildCommand: npm install && node fix-auth.js
    startCommand: node index.js
    plan: free
    # Set to private service to prevent public access
    private: true
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: COMMIT_FREQUENCY
        value: "*/30 * * * *"
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
